//go:build linux

package runtime

import "encoding/binary"

// bpfProgram is a compiled BPF program plus the tracepoint it attaches to. The
// bytecode is produced offline (from the C sources kept alongside this package)
// and embedded as raw instructions so loading needs no clang at runtime. Each
// program reserves a record in the ring buffer, fills the shared event layout
// (see decodeKernelEvent), and submits it.
//
// NOTE: the Insns below are placeholders for the offline-compiled bytecode. The
// build-and-embed step runs on a Linux toolchain; this repo keeps the loader,
// relocation, attach, and decode logic — the parts that are pure Go — and the
// bytecode is filled in by the Linux build. Until it is, loadProg rejects an
// empty program, so live mode fails loudly rather than loading a no-op.
type bpfProgram struct {
	// category/name identify the tracepoint, e.g. ("sched","sched_process_exec").
	category string
	name     string
	// insns is the raw BPF instruction stream (8 bytes per instruction).
	insns []byte
	// ringMapLoadOffset is the byte offset of the instruction that loads the
	// ring-buffer map fd, so relocate() can patch the real fd in at load time.
	ringMapLoadOffset int
}

// relocate returns the program's instructions with the ring-buffer map fd
// patched into the map-load instruction (BPF_LD_MAP_FD encodes the fd in the
// imm field of a wide load). Returning a copy keeps bpfPrograms immutable.
func (p bpfProgram) relocate(ringFD int) []byte {
	out := make([]byte, len(p.insns))
	copy(out, p.insns)
	if p.ringMapLoadOffset+8 <= len(out) {
		// imm sits in the last 4 bytes of the 8-byte instruction word.
		binary.LittleEndian.PutUint32(out[p.ringMapLoadOffset+4:], uint32(ringFD))
	}
	return out
}

// bpfPrograms maps a probe group to its compiled program + tracepoint. The
// tracepoint choices mirror the detection rules: process exec (rules_process),
// file open (rules_file), socket connect (rules_network), and kernel-module load
// (rules_kernel). The bytecode is embedded by the Linux build (see NOTE above).
var bpfPrograms = map[string]bpfProgram{
	"process": {category: "sched", name: "sched_process_exec", insns: embeddedProgProcess, ringMapLoadOffset: progProcessMapOff},
	"file":    {category: "syscalls", name: "sys_enter_openat", insns: embeddedProgFile, ringMapLoadOffset: progFileMapOff},
	"network": {category: "syscalls", name: "sys_enter_connect", insns: embeddedProgNetwork, ringMapLoadOffset: progNetworkMapOff},
	"syscall": {category: "syscalls", name: "sys_enter_finit_module", insns: embeddedProgSyscall, ringMapLoadOffset: progSyscallMapOff},
}

// The embedded bytecode blobs and their map-load offsets are generated by the
// offline Linux build step. They are declared here (empty) so the pure-Go loader
// type-checks everywhere; the Linux build overwrites this file's blobs with the
// compiled programs. An empty blob makes loadProg fail loudly (see loadProg).
var (
	embeddedProgProcess []byte
	embeddedProgFile    []byte
	embeddedProgNetwork []byte
	embeddedProgSyscall []byte
)

const (
	progProcessMapOff = 0
	progFileMapOff    = 0
	progNetworkMapOff = 0
	progSyscallMapOff = 0
)
