// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package runtime

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	sensorMapEnforceCfg     = "enforce_cfg"
	sensorMapEvents         = "events"
	sensorProgHandleConnect = "handle_connect"
	sensorProgHandleExec    = "handle_exec"
	sensorProgHandleOpenat  = "handle_openat"
	sensorProgOnBpf         = "on_bpf"
	sensorProgOnFinitModule = "on_finit_module"
	sensorProgOnInitModule  = "on_init_module"
	sensorProgOnMemfdCreate = "on_memfd_create"
	sensorProgOnMount       = "on_mount"
	sensorProgOnSetns       = "on_setns"
)

// loadSensor returns the embedded CollectionSpec for sensor.
func loadSensor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SensorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sensor: %w", err)
	}

	return spec, err
}

// loadSensorObjects loads sensor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sensorObjects
//	*sensorPrograms
//	*sensorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSensorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSensor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sensorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorSpecs struct {
	sensorProgramSpecs
	sensorMapSpecs
	sensorVariableSpecs
}

// sensorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
	HandleExec    *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleOpenat  *ebpf.ProgramSpec `ebpf:"handle_openat"`
	OnBpf         *ebpf.ProgramSpec `ebpf:"on_bpf"`
	OnFinitModule *ebpf.ProgramSpec `ebpf:"on_finit_module"`
	OnInitModule  *ebpf.ProgramSpec `ebpf:"on_init_module"`
	OnMemfdCreate *ebpf.ProgramSpec `ebpf:"on_memfd_create"`
	OnMount       *ebpf.ProgramSpec `ebpf:"on_mount"`
	OnSetns       *ebpf.ProgramSpec `ebpf:"on_setns"`
}

// sensorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorMapSpecs struct {
	EnforceCfg *ebpf.MapSpec `ebpf:"enforce_cfg"`
	Events     *ebpf.MapSpec `ebpf:"events"`
}

// sensorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorVariableSpecs struct {
}

// sensorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorObjects struct {
	sensorPrograms
	sensorMaps
	sensorVariables
}

func (o *sensorObjects) Close() error {
	return _SensorClose(
		&o.sensorPrograms,
		&o.sensorMaps,
	)
}

// sensorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorMaps struct {
	EnforceCfg *ebpf.Map `ebpf:"enforce_cfg"`
	Events     *ebpf.Map `ebpf:"events"`
}

func (m *sensorMaps) Close() error {
	return _SensorClose(
		m.EnforceCfg,
		m.Events,
	)
}

// sensorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorVariables struct {
}

// sensorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
	HandleExec    *ebpf.Program `ebpf:"handle_exec"`
	HandleOpenat  *ebpf.Program `ebpf:"handle_openat"`
	OnBpf         *ebpf.Program `ebpf:"on_bpf"`
	OnFinitModule *ebpf.Program `ebpf:"on_finit_module"`
	OnInitModule  *ebpf.Program `ebpf:"on_init_module"`
	OnMemfdCreate *ebpf.Program `ebpf:"on_memfd_create"`
	OnMount       *ebpf.Program `ebpf:"on_mount"`
	OnSetns       *ebpf.Program `ebpf:"on_setns"`
}

func (p *sensorPrograms) Close() error {
	return _SensorClose(
		p.HandleConnect,
		p.HandleExec,
		p.HandleOpenat,
		p.OnBpf,
		p.OnFinitModule,
		p.OnInitModule,
		p.OnMemfdCreate,
		p.OnMount,
		p.OnSetns,
	)
}

func _SensorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sensor_bpfel.o
var _SensorBytes []byte
