FROM alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad4d
RUN adduser -D app
USER app
HEALTHCHECK CMD wget -q -O- http://localhost:8080/healthz || exit 1
ENTRYPOINT ["/app/server"]
